import sys
import struct
import numpy as np
import nibabel as nib
from pathlib import Path
from datetime import datetime

# ── Config ────────────────────────────────────────────────────────────────────
BASE_DIR   = Path(__file__).parent
SEG_DIR    = BASE_DIR / "test_data" / "results" / "totalsegmentator" / "segmentations"
OUTPUT_DIR = BASE_DIR / "test_data" / "results" / "slicer_nrrd"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# ── 12-class definitions — names + colors ─────────────────────────────────────
# Color format: (R, G, B) 0-255
SEGMENTS = {
    1:  {"name": "Frontal_Lobe",            "color": (255, 0,   0  )},
    2:  {"name": "Parietal_Lobe",           "color": (0,   0,   255)},
    3:  {"name": "Temporal_Lobe",           "color": (255, 165, 0  )},
    4:  {"name": "Occipital_Lobe",          "color": (0,   255, 0  )},
    5:  {"name": "Cerebellum",              "color": (255, 0,   255)},
    6:  {"name": "Lateral_Ventricle_Left",  "color": (255, 255, 0  )},
    7:  {"name": "Lateral_Ventricle_Right", "color": (0,   255, 255)},
    8:  {"name": "Basal_Ganglia_Left",      "color": (128, 0,   128)},
    9:  {"name": "Basal_Ganglia_Right",     "color": (255, 105, 180)},
    10: {"name": "Brainstem",               "color": (255, 255, 255)},
    11: {"name": "Thalamus_Left",           "color": (255, 140, 0  )},
    12: {"name": "Thalamus_Right",          "color": (139, 69,  19 )},
}


def convert_to_seg_nrrd(nifti_path: Path, output_path: Path):
    """
    Convert a labeled NIfTI segmentation to 3D Slicer .seg.nrrd format.
    The .seg.nrrd file embeds segment names and colors so Slicer
    displays them automatically without any manual setup.
    """
    seg_img  = nib.load(str(nifti_path))
    seg_data = seg_img.get_fdata().astype(np.uint8)
    affine   = seg_img.affine
    zooms    = seg_img.header.get_zooms()

    # Find which labels actually exist in this scan
    present_labels = sorted([l for l in np.unique(seg_data) if l > 0])
    print(f"  Labels present: {present_labels}")

    # ── Build NRRD header ─────────────────────────────────────────────────────
    # 3D Slicer .seg.nrrd uses a specific header format with segment metadata
    sx, sy, sz = seg_data.shape
    dx, dy, dz = float(zooms[0]), float(zooms[1]), float(zooms[2])

    # Origin from affine
    ox = float(affine[0, 3])
    oy = float(affine[1, 3])
    oz = float(affine[2, 3])

    # Direction cosines from affine (normalized)
    def norm_col(i):
        col = affine[:3, i]
        n   = np.linalg.norm(col)
        return col / n if n > 0 else col

    d0 = norm_col(0)
    d1 = norm_col(1)
    d2 = norm_col(2)

    # Build header lines
    header_lines = [
        "NRRD0005",
        "# Segmentation created by TNSQAI pipeline",
        f"# Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "type: unsigned char",
        "dimension: 3",
        f"space: left-posterior-superior",
        f"sizes: {sx} {sy} {sz}",
        f"space directions: ({d0[0]*dx:.6f},{d0[1]*dx:.6f},{d0[2]*dx:.6f}) "
                          f"({d1[0]*dy:.6f},{d1[1]*dy:.6f},{d1[2]*dy:.6f}) "
                          f"({d2[0]*dz:.6f},{d2[1]*dz:.6f},{d2[2]*dz:.6f})",
        "kinds: domain domain domain",
        f"labels: \"0\" {' '.join(str(l) for l in present_labels)}",  # ← no quotes around labels, avoids backslash issue
        f"space origin: ({ox:.6f},{oy:.6f},{oz:.6f})",
        "encoding: raw",
    ]

    # ── Slicer-specific segment metadata ──────────────────────────────────────
    # This is the key part — Slicer reads these fields to set names and colors
    header_lines.append(f"Segmentation_ContainedRepresentationNames: Binary labelmap|Closed surface|")
    header_lines.append(f"Segmentation_MasterRepresentation: Binary labelmap")
    header_lines.append(f"Segmentation_ReferenceImageExtentOffset: 0 0 0")

    for idx, label in enumerate(present_labels):
        if label not in SEGMENTS:
            continue
        seg = SEGMENTS[label]
        r, g, b = seg["color"]
        name    = seg["name"]
        # Slicer color format is 0.0-1.0
        rf = round(r / 255.0, 6)
        gf = round(g / 255.0, 6)
        bf = round(b / 255.0, 6)

        header_lines.append(f"Segment{idx}_Color: {rf} {gf} {bf}")
        header_lines.append(f"Segment{idx}_ColorAutoGenerated: 0")
        header_lines.append(f"Segment{idx}_Extent: 0 {sx-1} 0 {sy-1} 0 {sz-1}")
        header_lines.append(f"Segment{idx}_ID: Segment_{idx+1}")
        header_lines.append(f"Segment{idx}_LabelValue: {label}")
        header_lines.append(f"Segment{idx}_Layer: 0")
        header_lines.append(f"Segment{idx}_Name: {name}")
        header_lines.append(f"Segment{idx}_NameAutoGenerated: 0")
        header_lines.append(f"Segment{idx}_Tags: Segmentation.Status:inprogress|")

    # ── Write NRRD file ───────────────────────────────────────────────────────
    with open(output_path, 'wb') as f:
        # Write header as ASCII
        for line in header_lines:
            f.write((line + "\n").encode('utf-8'))
        # Blank line separates header from data
        f.write(b"\n")
        # Write raw binary data (C-order, uint8)
        f.write(seg_data.astype(np.uint8).tobytes(order='F'))  # Fortran order for NRRD

    size_mb = output_path.stat().st_size / (1024 * 1024)
    print(f"  Saved: {output_path.name} ({size_mb:.1f} MB)")
    return len(present_labels)


def main():
    print(f"{'='*62}")
    print(f"  NIfTI Segmentation → 3D Slicer .seg.nrrd Converter")
    print(f"{'='*62}")
    print(f"  Input  : {SEG_DIR}")
    print(f"  Output : {OUTPUT_DIR}")
    print(f"  Colors : Embedded automatically — no manual entry needed")
    print(f"{'='*62}\n")

    # Single patient mode
    if len(sys.argv) > 1:
        patient_id = sys.argv[1]
        nifti_path = SEG_DIR / f"{patient_id}_seg.nii.gz"
        if not nifti_path.exists():
            print(f"Not found: {nifti_path}")
            print(f"Available:")
            for f in sorted(SEG_DIR.glob("*_seg.nii.gz")):
                print(f"  {f.stem.replace('_seg','')}")
            return
        nifti_files = [nifti_path]
    else:
        nifti_files = sorted(SEG_DIR.glob("*_seg.nii.gz"))

    if not nifti_files:
        print(f"No *_seg.nii.gz files found in {SEG_DIR}")
        return

    print(f"  Found {len(nifti_files)} patients\n")

    success = 0
    failed  = []

    for idx, nifti_path in enumerate(nifti_files, 1):
        patient_id  = nifti_path.name.replace("_seg.nii.gz", "")
        output_path = OUTPUT_DIR / f"{patient_id}_seg.seg.nrrd"

        print(f"[{idx}/{len(nifti_files)}] {patient_id}")

        try:
            n_labels = convert_to_seg_nrrd(nifti_path, output_path)
            print(f"  ✅ {n_labels} segments with colors embedded\n")
            success += 1
        except Exception as e:
            print(f"  ❌ FAILED: {e}\n")
            failed.append(patient_id)

    print(f"{'='*62}")
    print(f"  DONE — {success} files converted")
    if failed:
        print(f"  Failed: {', '.join(failed)}")
    print(f"\n  How to open in 3D Slicer:")
    print(f"  File → Add Data → select {patient_id}_seg.seg.nrrd")
    print(f"  → Colors and names appear AUTOMATICALLY ✅")
    print(f"{'='*62}\n")


if __name__ == "__main__":
    main()